# Generated by Django 3.0.2 on 2020-03-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191216_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
