# Generated by Django 3.0.2 on 2020-04-05 10:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200327_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='SOME STRING', max_length=140),
        ),
    ]
