# Generated by Django 3.0.2 on 2020-01-18 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
