# Generated by Django 3.0.2 on 2020-04-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='post',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='post_id',
        ),
    ]
