# Generated by Django 3.0.2 on 2020-04-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200415_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='post',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='post_id',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
