# Generated by Django 3.0.2 on 2020-04-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200415_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
